<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Maria Yasin">

<title>Programming with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="R Programming Short Project 1_files/libs/clipboard/clipboard.min.js"></script>
<script src="R Programming Short Project 1_files/libs/quarto-html/quarto.js"></script>
<script src="R Programming Short Project 1_files/libs/quarto-html/popper.min.js"></script>
<script src="R Programming Short Project 1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="R Programming Short Project 1_files/libs/quarto-html/anchor.min.js"></script>
<link href="R Programming Short Project 1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="R Programming Short Project 1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="R Programming Short Project 1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="R Programming Short Project 1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="R Programming Short Project 1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Programming with R</h1>
<p class="subtitle lead">Short Project 1</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Maria Yasin </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="descriptive-statistics-and-graphs-of-baby-names-in-ireland-1964-2021." class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics-and-graphs-of-baby-names-in-ireland-1964-2021.">Descriptive Statistics and Graphs of Baby Names in Ireland (1964-2021).</h2>
<p>In the first exercise, we use a dataset that contains baby names (1964–2021) for the Republic of Ireland, released annually by the Central Statistics Office. Due to confidentiality reasons, only names with at least three instances in the relevant year are included. The data frame <code>iebabynames</code>is part of the <a href="https://github.com/stefan-mueller/iebabynames"><strong>iebabynames</strong> R package</a>. You need to install two packages for this exercise: <strong>devtools</strong> (which allows installing packages from other sources than CRAN (which is the default)) and the <strong>iebabynames</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># execute these lines in your console (only once!)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"devtools"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"stefan-mueller/iebabynames"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="part-1" class="level4">
<h4 class="anchored" data-anchor-id="part-1">Part 1</h4>
<p>After installing the package in your console, we load the <strong>iebabynames</strong> package and <strong>tidyverse</strong>. Inspect the data frame <code>iebabynames</code>. What is the number of observations? What is the unit of analysis in this dataset?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(iebabynames)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># load the tidyverse</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Number of observations</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(iebabynames)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 74661</code></pre>
</div>
</div>
<p><em>There are a total of 74661 observations.</em></p>
<p><em>The unit of analysis in this data set is the baby names in the years 1964-2021.</em></p>
</section>
<section id="part-2" class="level4">
<h4 class="anchored" data-anchor-id="part-2">Part 2</h4>
<p>Filter only observations that contain information on your own name. What is the number of observations of this filtered dataset? Do you have an observation for each year in the dataset (1964-2021)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Filter the dataset with name 'Maria'</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>my_babyname <span class="ot">&lt;-</span> <span class="fu">filter</span>(iebabynames, name <span class="sc">==</span> <span class="st">"Maria"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Check the total number of observations</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(my_babyname)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 58</code></pre>
</div>
</div>
<p><em>There are a total of 58 observations in the new dataset.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check for na values</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(my_babyname<span class="sc">$</span>n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check for any observation with count n = 0</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(my_babyname<span class="sc">$</span>n <span class="sc">==</span> <span class="st">"0"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p><em>Since we have checked for any NA values or any observation corresponding the variable count ‘n’ = 0, we conclude that there is an observation for each year (1964-2021) in the dataset. </em></p>
</section>
<section id="part-3" class="level4">
<h4 class="anchored" data-anchor-id="part-3">Part 3</h4>
<p>Create a plot with the year on the x-axis and the count of babynames (<code>n</code>) on the y-axis. Add points for each observation to this plot (=basically, create a scatterplot). As always, make sure to add meaningful variable names.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Scatter plot</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> my_babyname, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> n, <span class="at">colour =</span> year)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Count of baby name 'Maria'"</span> , <span class="at">title =</span> <span class="st">"Count of baby name per year (1964-2021)"</span>) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1960</span>, <span class="at">to =</span> <span class="dv">2021</span>, <span class="at">by =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-Programming-Short-Project-1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="part-4" class="level4">
<h4 class="anchored" data-anchor-id="part-4">Part 4</h4>
<p>Add a line that connects the plot. Change the ggplot2 scheme to <code>theme_minimal()</code>. Describe the developments of the name’s popularity over time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#geom_line</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> my_babyname, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> n, <span class="at">colour =</span> year)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Count of baby name 'Maria'"</span> , <span class="at">title =</span> <span class="st">"Count of baby name per year (1964-2021)"</span>) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1960</span>, <span class="at">to =</span> <span class="dv">2021</span>, <span class="at">by =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-Programming-Short-Project-1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Looking at the graph, we can see that the name ‘Maria’ was very popular during the 60s and 70s up until 1980, however, after 1980, we see a significant decline in the count, this indicates that the popularity of the name decreased during the following 2 decades (1980-2000), the count started rising again in the early 2000s (2000-2010), however, we can say that the popularity of the name has been decreasing during the last decade as we keep seeing a fall in the name count. </em></p>
</section>
<section id="part-5" class="level4">
<h4 class="anchored" data-anchor-id="part-5">Part 5</h4>
<p>Rerun this plot, but use the proportion instead. List one advantage of using counts and one advantage of using proportions to compare developments over time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> my_babyname, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> prop, <span class="at">colour =</span> year)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Proportion of baby name 'Maria'"</span> , <span class="at">title =</span> <span class="st">"Proportion of baby name per year (1964-2021)"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1960</span>, <span class="at">to =</span> <span class="dv">2021</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-Programming-Short-Project-1_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>- Counts give a very concise idea about the change in the variable over time as we can see the exact number of times a variable has appeared throughout a certain time period.</em></p>
<p><em>- Proportions are a good way to see the change over time with respect to the overall change in population. They can also help us see the change in one variable over time given the other features remain consistent. Proportions are also useful in enlarging or reducing an image to scale depending on the nature of the change over time.</em></p>
</section>
<section id="part-6" class="level4">
<h4 class="anchored" data-anchor-id="part-6">Part 6</h4>
<p>Filter the 10 most frequent male and female names (based on <code>rank</code>) in 2021 and store this filtered object as a new data frame (you can use <code>slice_max()</code> or simply filter based on the <code>rank</code> variable. Remember to use meaningful names for objects (e.g., <code>dat_top10_2021</code> instead of <code>dat1</code>). What are the counts of the most frequent male name and most frequent female name in 2021?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Filtering the data for 2021 cases only</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>dat_2021 <span class="ot">&lt;-</span> <span class="fu">filter</span>(iebabynames, year <span class="sc">==</span> <span class="st">"2021"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Getting top 10 male and female names of 2021</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>dat_top_10_2021 <span class="ot">&lt;-</span> dat_2021[<span class="fu">order</span>(dat_2021<span class="sc">$</span>rank),]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>dat_top_10_2021 <span class="ot">&lt;-</span> dat_top_10_2021[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>,]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>dat_top_10_2021</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     year    sex    name   n rank        prop   prop_sex
1    2021 Female   Fiadh 424    1 0.008322211 0.01733230
1124 2021   Male    Jack 667    1 0.013091780 0.02518407
2    2021 Female   Grace 412    2 0.008086677 0.01684176
1125 2021   Male    Noah 475    2 0.009323232 0.01793468
3    2021 Female   Emily 388    3 0.007615608 0.01586069
1126 2021   Male   James 442    3 0.008675512 0.01668869
4    2021 Female  Sophie 336    4 0.006594960 0.01373503
1127 2021   Male   Conor 360    4 0.007066028 0.01359260
5    2021 Female   Éabha 288    5 0.005652822 0.01177288
1128 2021   Male    Rían 357    5 0.007007145 0.01347933
6    2021 Female    Lucy 287    6 0.005633195 0.01173200
1129 2021   Male    Liam 353    6 0.006928633 0.01332830
7    2021 Female     Mia 279    7 0.005476172 0.01140498
1130 2021   Male Charlie 345    7 0.006771610 0.01302624
8    2021 Female     Ava 272    8 0.005338777 0.01111883
1131 2021   Male  Daniel 325    8 0.006379053 0.01227110
9    2021 Female    Lily 271    9 0.005319149 0.01107795
1132 2021   Male Cillian 322    9 0.006320170 0.01215783
10   2021 Female    Ella 268   10 0.005260265 0.01095532
1133 2021   Male   Tadhg 318   10 0.006241658 0.01200680</code></pre>
</div>
</div>
<p><em>Our new dataframe shows the count of the top 10 male and female names of 2021. According to the dataset, the most frequently used female name of 2021 is ‘Fiadh’, with a count of 424. On the other hand, the most frequent male name of 2021 is ‘Jack’, with a count of 667.</em></p>
</section>
<section id="part-7" class="level4">
<h4 class="anchored" data-anchor-id="part-7">Part 7</h4>
<p>Create a bar plot that shows the absolute counts in <em>descending</em> order, using the data frame created in question 6. Plot the frequency (<code>n</code>) on the x-axis and the name on the y-axis. Note: since you already aggregated the data, use <code>geom_bar(stat = "identity")</code>. Use different colours of the bars for male and female names (add <code>fill = sex</code> into your <code>aes()</code> call). [10 points]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dat_top_10_2021, <span class="fu">aes</span>(<span class="at">x=</span> n, <span class="at">y=</span> <span class="fu">reorder</span>(name,n), <span class="at">fill =</span> sex, <span class="at">width =</span> <span class="fl">0.8</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Name Count"</span>, <span class="at">y =</span> <span class="st">"Name"</span>, <span class="at">title =</span> <span class="st">"Absolute Counts of Names in Descending Order"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>plot </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-Programming-Short-Project-1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="part-8" class="level4">
<h4 class="anchored" data-anchor-id="part-8">Part 8</h4>
<p>Use the main dataset, but filter only the names “John” and “Paul”. Create a faceted plot that shows the developments of frequencies (<code>n</code>) of the names <code>John</code> and <code>Paul</code> using <code>geom_point()</code> and <code>geom_line()</code>. You can use <code>facet_wrap(~name)</code> to get a box for each name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>dat_john_paul <span class="ot">&lt;-</span> <span class="fu">filter</span>(iebabynames, name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"John"</span>,<span class="st">"Paul"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat_john_paul, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> n, <span class="at">colour =</span> year)) <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1960</span>, <span class="at">to =</span> <span class="dv">2021</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>name) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Name Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-Programming-Short-Project-1_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="part-9" class="level4">
<h4 class="anchored" data-anchor-id="part-9">Part 9</h4>
<p><strong>BONUS</strong> What are the frequencies of both names in 1978 and 1979? What could be the reason for the drastic spike in “John” and “Paul” in 1979?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Filter the dataset for the years 1978 and 1979</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(dat_john_paul, year <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"1978"</span>,<span class="st">"1979"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  year  sex name    n rank       prop   prop_sex
1 1979 Male John 2707    1 0.03894236 0.07500485
2 1979 Male Paul 1492    3 0.02146361 0.04133995
3 1978 Male John 2280    1 0.03396344 0.06607738
4 1978 Male Paul 1343    3 0.02000566 0.03892190</code></pre>
</div>
</div>
<p><em>During 1978, ‘John’ appears 2280 times and ‘Paul’ appears 1343 times. During 1979, ‘John’ appears 2707 times, whereas, ‘Paul’ appears 1492 times.</em></p>
<p><em>One possible reason for the drastic spike in the 2 names could be that the names appeared in some popular movie or TV show and grabbed people’s attention.</em></p>
</section>
</section>
<section id="analysing-survey-data-voting-behaviour-during-the-brexit-referendum." class="level2">
<h2 class="anchored" data-anchor-id="analysing-survey-data-voting-behaviour-during-the-brexit-referendum.">Analysing Survey Data: Voting Behaviour during the Brexit Referendum.</h2>
<p>This exercise uses data from the British Election Study collected shortly before the Brexit Referendum. It will help us analyse how age and education levels relate to voting “leave” or “remain”. The data are described and used in Sara Hobolt’s paper “The Brexit vote: a divided nation, a divided continent” published in the Journal of European Public Policy in 2016. The dataset is part of the 7th Wave of the British Election Study, constituting the pre-campaign “Panel Survey Study of the 2016 EU Referendum”, conducted before the referendum. The sample size is much larger than usual election studies, allowing for a fine-grained analysis of vote choice based on age and education.</p>
<section id="part-1-1" class="level4">
<h4 class="anchored" data-anchor-id="part-1-1">Part 1</h4>
<p>What is the number of observations in this dataset? Is the survey representative of the outcome of the Brexit vote? Use <code>prop.table(table(dat_brexit$leave))</code> and compare the percentage of remain (0) and leave (=1) voters with the referendum outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load dataset: make sure bes_brexit.csv is in the same folder as this Quarto document</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>dat_brexit <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"dat_brexit.csv"</span>, <span class="at">fileEncoding =</span> <span class="st">"utf-8"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Total number of observations</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(dat_brexit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30895</code></pre>
</div>
</div>
<p><em>There are a total of 30,895 observations in the dataset.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Find the proportion </span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(dat_brexit<span class="sc">$</span>leave))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        0         1 
0.5117672 0.4882328 </code></pre>
</div>
</div>
<p><em>51% people voted remain and 49% of the voters voted leave.</em></p>
<p><em>In this survey the majority people voted remain (i.e., 51%) as opposed to leave (i.e., 49%), on the other hand, in the actual referendum outcome, UK voted to leave the EU by a majority i.e., 52% (remain votes equal to 48%), since the difference between the survey outcome and the actual referendum outcome is not very big, we can conclude that the survey is somewhat representative of the actual outcome of the Brexit vote. However, we should take into account that this small difference is crucial.</em></p>
</section>
<section id="part-2-1" class="level4">
<h4 class="anchored" data-anchor-id="part-2-1">Part 2</h4>
<p>Remove missing values for the “leave” and “education” variables. Then group the data frame by education level and use <code>summarise()</code> to get the proportions of respondents who voted “leave” in each education category. [Note:<code>leave</code> is a binary variable (0/1) which you can use to calculate the proportion. Since we have only two values, coded 0 and 1, the proportion can be calculated using <code>mean()</code>.] Assign this data frame to a new object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove NA values from 'leave' variable</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>dat_brexit <span class="ot">&lt;-</span> <span class="fu">filter</span>(dat_brexit[<span class="sc">!</span><span class="fu">is.na</span>(dat_brexit<span class="sc">$</span>leave),])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove NA values from 'education' variable</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>dat_brexit <span class="ot">&lt;-</span> <span class="fu">filter</span>(dat_brexit[<span class="sc">!</span><span class="fu">is.na</span>(dat_brexit<span class="sc">$</span>education),])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Group the data by education level</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarise the grouped variable to see the proportions of respondents who voted "leave"</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Assign the df to a new object</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>brexit_grp_education <span class="ot">=</span> dat_brexit <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(education)  <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">summarise</span>(<span class="at">leave =</span> <span class="fu">mean</span>(leave),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                              <span class="at">.groups =</span> <span class="st">'drop'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>brexit_grp_education</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 x 2
  education                          leave
  &lt;chr&gt;                              &lt;dbl&gt;
1 Education advanced level (A level) 0.471
2 No secondary qualification         0.731
3 Postgraduate degree                0.250
4 Secondary qualification            0.658
5 Undergraduate degree               0.384</code></pre>
</div>
</div>
</section>
<section id="part-3-1" class="level4">
<h4 class="anchored" data-anchor-id="part-3-1">Part 3</h4>
<p>Re-level the education variable in the data frame created in the previous question. For comparability, order the education levels from “low” to “high”, i.e.:</p>
<ul>
<li>No secondary qualification</li>
<li>Secondary qualification</li>
<li>Education advanced level (A level)</li>
<li>Undergraduate degree</li>
<li>Postgraduate degree</li>
</ul>
<p>Afterwards, create a bar plot showing the proportions of leave votes on the horizontal x-axis and the education levels on the vertical y-axis. What could we do to make the axis labels more readable? Try to add <code>coord_flip()</code> to your graph and check whether/how it makes a difference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-level the education variable</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>brexit_grp_education<span class="sc">$</span>education <span class="ot">&lt;-</span> <span class="fu">factor</span>(brexit_grp_education<span class="sc">$</span>education, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No secondary qualification"</span>, <span class="st">"Secondary qualification"</span>, <span class="st">"Education advanced level (A level)"</span>,<span class="st">"Undergraduate degree"</span>,<span class="st">"Postgraduate degree"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Barplot</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(brexit_grp_education, <span class="at">mapping =</span>  <span class="fu">aes</span>(<span class="at">x =</span> leave, <span class="at">y =</span> education, <span class="at">fill =</span> education))  <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">'identity'</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Proportion of leave votes"</span>, <span class="at">y =</span> <span class="st">"Education level"</span>, <span class="at">title =</span> <span class="st">"Proportion of leave votes based on education level"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Purples"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-Programming-Short-Project-1_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Barplot with coord_flip</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(brexit_grp_education, <span class="at">mapping =</span>  <span class="fu">aes</span>(<span class="at">x =</span> leave, <span class="at">y =</span> education, <span class="at">fill =</span> education))  <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">'identity'</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Proportion of leave votes"</span>, <span class="at">y =</span> <span class="st">"Education level"</span>, <span class="at">title =</span> <span class="st">"Proportion of leave votes based on education level"</span>) <span class="sc">+</span> <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Purples"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-Programming-Short-Project-1_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>In order to make the graph look more readable, we can put proportions on y-axis and education levels on x-axis.</em></p>
<p><em>After adding ‘coord_flip()’ to our command, we see a change in the dimensions of the barplot as the education level appears on the x-axis now and the proportion of leave votes appears on the y-axis.</em></p>
</section>
<section id="part-4-1" class="level4">
<h4 class="anchored" data-anchor-id="part-4-1">Part 4</h4>
<p>Interpret the graph by describing the relationship between education levels and voting “leave”.</p>
<p><em>Looking at the barplot, we can see that there is an inverse relationship between the level of education attained and proportion of leave votes. As the level of education increases, the proportion of leave votes decreases i.e., No secondary qualification corresponds to the highest proportion of leave votes, whereas, Postgraduate degree corresponds to the lowest proportion of leave votes. </em></p>
</section>
<section id="part-5-1" class="level4">
<h4 class="anchored" data-anchor-id="part-5-1">Part 5</h4>
<p>What is the range of the “age” variable? What is the lowest and highest value of the “age” variable? Create a new object that groups the original data frame by age, and calculate the proportion of “leave voters” for each age.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Find the 'age' range</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(dat_brexit<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18 97</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Find the minimum and maximum age</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(dat_brexit<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(dat_brexit<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 97</code></pre>
</div>
</div>
<p><em>The variable ‘age’ ranges from 18 to 97 where the minimum age is 18 and the maximum age is 97.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Group the data by age</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarise the grouped variable to see the proportions of respondents who voted "leave"</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Assign the df to a new object</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>brexit_grp_age <span class="ot">=</span> dat_brexit <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(age)  <span class="sc">%&gt;%</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">summarise</span>(<span class="at">leave =</span> <span class="fu">mean</span>(leave),</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">.groups =</span> <span class="st">'drop'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>brexit_grp_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 76 x 2
     age leave
   &lt;int&gt; &lt;dbl&gt;
 1    18 0.222
 2    19 0.237
 3    20 0.195
 4    21 0.198
 5    22 0.213
 6    23 0.231
 7    24 0.214
 8    25 0.271
 9    26 0.242
10    27 0.317
# ... with 66 more rows</code></pre>
</div>
</div>
</section>
<section id="part-6-1" class="level4">
<h4 class="anchored" data-anchor-id="part-6-1">Part 6</h4>
<p>Create a plot with the age on the x-axis and the proportion of leave voters on the y-axis. Add <code>geom_smooth(method = "loess")</code>. Change the limits of the y-axis to a range from 0 to 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Change the limits of the y-axis from 0 to 1</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> brexit_grp_age, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> leave)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">"Proportion of leave votes"</span> , <span class="at">title =</span> <span class="st">"Proportion of leave votes by age"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="R-Programming-Short-Project-1_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="part-7-1" class="level4">
<h4 class="anchored" data-anchor-id="part-7-1">Part 7</h4>
<p>Interpret the relationship between age and voting “leave”. By inspecting the graph, what proportion of respondents at the ages of 18, 50, and 75 voted “leave” (roughly speaking)?</p>
<p><em>The scatter plot indicates a positive correlation between age and proportion of leave votes. As the age increases, the proportion of leave votes increases as well, i.e., younger people have smaller proportion of leave votes whereas, older people have a higher proportion of leave votes.</em></p>
<p><em>-At age 18, the proportion of leave vote is roughly 0.22.</em></p>
<p><em>-At age 50, the proportion of leave vote is roughly 0.55.</em></p>
<p><em>-At age 75, the proportion of leave vote is roughly 0.67.</em></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>